{
 "title": "SpaceCraft Alpha",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Bank Send TXs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Recent TX (Bank Send)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT\n  from_address,\n  to_address,\n  amount,\n  time\nFROM transactions\nORDER BY time DESC\nLIMIT 20;",
     "rawQueryText": "SELECT\n  from_address,\n  to_address,\n  amount,\n  time\nFROM transactions\nORDER BY time DESC\nLIMIT 20;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Top Sending Bank TXs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT\n  from_address,\n  count(*) AS num_transactions\nFROM transactions\nGROUP BY from_address\nORDER BY num_transactions DESC\nLIMIT 10;",
     "rawQueryText": "SELECT\n  from_address,\n  count(*) AS num_transactions\nFROM transactions\nGROUP BY from_address\nORDER BY num_transactions DESC\nLIMIT 10;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Bank Send TXs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT\n  time,\n  count(*) AS num_transactions\nFROM transactions\nGROUP BY strftime('%Y-%m-%d %H', time)\nORDER BY \"time\";",
     "rawQueryText": "SELECT\n  time,\n  count(*) AS num_transactions\nFROM transactions\nGROUP BY strftime('%Y-%m-%d %H', time)\nORDER BY \"time\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Block x Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT\n  time,\n  count(*) AS num_blocks\nFROM blocks\nGROUP BY strftime('%Y-%m-%d %H:%M:00', time)\nORDER BY \"time\";\n",
     "rawQueryText": "SELECT\n  time,\n  count(*) AS num_blocks\nFROM blocks\nGROUP BY strftime('%Y-%m-%d %H:%M:00', time)\nORDER BY \"time\";\n",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Last Block synced",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT height\nFROM blocks\nORDER BY height DESC\nLIMIT 1;",
     "rawQueryText": "SELECT height\nFROM blocks\nORDER BY height DESC\nLIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Blocks x Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT\n  time,\n  count(*) AS num_blocks\nFROM blocks\nGROUP BY strftime('%Y-%m-%d', time)\nORDER BY \"time\";",
     "rawQueryText": "SELECT\n  time,\n  count(*) AS num_blocks\nFROM blocks\nGROUP BY strftime('%Y-%m-%d', time)\nORDER BY \"time\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Blocks x Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT\n  time,\n  count(*) AS num_blocks\nFROM blocks\nGROUP BY strftime('%Y-%m-%d %H:00:00', time)\nORDER BY \"time_group\";\n",
     "rawQueryText": "SELECT\n  time,\n  count(*) AS num_blocks\nFROM blocks\nGROUP BY strftime('%Y-%m-%d %H:00:00', time)\nORDER BY \"time_group\";\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Blocks x Softare version",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT\n  version,\n  count(*) AS num_blocks\nFROM blocks\nGROUP BY version\nORDER BY num_blocks DESC;",
     "rawQueryText": "SELECT\n  version,\n  count(*) AS num_blocks\nFROM blocks\nGROUP BY version\nORDER BY num_blocks DESC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "targets": [
    {
     "queryText": "SELECT\n  proposer_address_raw AS Proposer,\n  max(height) AS last_block_height,\n  max(time) AS last_block_time\nFROM blocks\nGROUP BY proposer_address_raw\nORDER BY last_block_time DESC;",
     "rawQueryText": "SELECT\n  proposer_address_raw AS Proposer,\n  max(height) AS last_block_height,\n  max(time) AS last_block_time\nFROM blocks\nGROUP BY proposer_address_raw\nORDER BY last_block_time DESC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Blocks frequency of a Proposer x Day",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 32 },
   "targets": [
    {
     "queryText": "SELECT\n  proposer_address_raw,\n  strftime('%Y-%m-%d', time) AS day,\n  count(*) AS num_blocks\nFROM blocks\nGROUP BY proposer_address_raw, day\nORDER BY proposer_address_raw, day;",
     "rawQueryText": "SELECT\n  proposer_address_raw,\n  strftime('%Y-%m-%d', time) AS day,\n  count(*) AS num_blocks\nFROM blocks\nGROUP BY proposer_address_raw, day\nORDER BY proposer_address_raw, day;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}